apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: container-image
    newName: node:latest
resources:
  - https://github.com/mcaballeropinto/kustomize-github-action-test.git/remote-k8s
