name: Test

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.deployment.ref }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Find git
        run: |
          echo "Path env var: $PATH"
          echo "whereis command result:"
          whereis git
          echo "Git version"
          git --version

      - name: Run Go script test
        run: go run test.go

      - name: Run kustomize build
        run: kustomize build ./k8s
